### ISSUE TITLE
how to use pair-wise bert?

### ISSUE THREAD

**Issue by chaochaoSZ** [myeclipse/wsdm_cup_2020_solution#3]
I have read your project, maybe you don't use pair-wise bert?
Can you show some detail how pair-wise bert been used in this project?

In the paper, you said you have used the pair-wise bert and find pair-wise is better than point-wise, but when I checked the project, maybe you aren't use this?

Don't know if I'm right.

Thank you.

**Comment by myeclipse** [comment]
You can find the pairwise-bert in rank/pairwise_bert :)
